apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    environment: production
    app: shopnova
    kubernetes.io/metadata.name: prod
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    environment: development
    app: shopnova
    kubernetes.io/metadata.name: dev
