# DEV Secrets — same structure as prod, can use test credentials
apiVersion: v1
kind: Secret
metadata:
  name: shopnova-secrets
  namespace: dev
type: Opaque
stringData:
  AUTH_MONGO_URI: "mongodb://auth-db:27017/authdb-dev"
  PRODUCT_MONGO_URI: "mongodb://product-db:27017/productdb-dev"
  ORDER_MONGO_URI: "mongodb://order-db:27017/orderdb-dev"
  JWT_SECRET: "dev-jwt-secret-change-for-real-testing"
  EMAIL_USER: "your-gmail@gmail.com"
  EMAIL_PASS: "your-gmail-app-password"
