# Product Service â€” prod values (main branch)
namespace: prod

image:
  repository: abhinavbabu33/shopnova-product-service
  tag: product-service-v0.2.0
  pullPolicy: Always

replicaCount: 1
port: 8002

hpa:
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 70
  memoryUtilization: 80

resources:
  requests:
    cpu: 128m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

rollout:
  autoPromotion: false   # prod — manual promotion required
