# Auth Service — dev overrides (dev branch)
namespace: dev

image:
  tag: dev-5146208

hpa:
  maxReplicas: 2

resources:
  requests:
    cpu: 64m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
